// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Emotionpedia",
    platforms: [
        .iOS("17.5")
    ],
    products: [
        .iOSApplication(
            name: "Emotionpedia",
            targets: ["AppModule"],
            bundleIdentifier: "vitoria.beltrao.sscemotionpedia25",
            teamIdentifier: "FJ88J69NXX",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight
            ],
            capabilities: [
                .microphone(purposeString: "Allow microphone access to hear you!"),
                .camera(purposeString: "Allow camera access to see you!"),
                .photoLibraryAdd(purposeString: "Allow library access to save your picture!"),
                .speechRecognition(purposeString: "Allow speech recognition so we can understand the numbers you say!")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)